name: ci

on:
  pull_request:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install Node.js
        uses: actions/setup-node@v1
        with:
          node-version:  12.x

      - name: Install dependencies
        run: yarn

      - name: Lint
        run: yarn lint

      - name: Unit/Integration tests
        run: yarn test:ci

      # - name: E2E tests
      #   run: yarn test:e2e:ci
